print('What is your name?: ')
name = input('>')
print('Hello', name)
print('Your name has', len(name), 'letters')
print('What is your age?:')
age = int(input('>'))
print('Great.', 'You will be', str(age + 1), 'next year.')
